package com.test.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.test.greendao.bean.Student;
import com.test.greendao.bean.Teacher;
import com.test.greendao.more2more.JoinEntity;
import com.test.greendao.more2more.More2Bean;
import com.test.greendao.more2more.MoreBean;
import com.test.greendao.one2more.Course;
import com.test.greendao.one2more.Students;
import com.test.greendao.one_2_one.Head;
import com.test.greendao.one_2_one.Person;

import com.test.greendao.dao.StudentDao;
import com.test.greendao.dao.TeacherDao;
import com.test.greendao.dao.JoinEntityDao;
import com.test.greendao.dao.More2BeanDao;
import com.test.greendao.dao.MoreBeanDao;
import com.test.greendao.dao.CourseDao;
import com.test.greendao.dao.StudentsDao;
import com.test.greendao.dao.HeadDao;
import com.test.greendao.dao.PersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig joinEntityDaoConfig;
    private final DaoConfig more2BeanDaoConfig;
    private final DaoConfig moreBeanDaoConfig;
    private final DaoConfig courseDaoConfig;
    private final DaoConfig studentsDaoConfig;
    private final DaoConfig headDaoConfig;
    private final DaoConfig personDaoConfig;

    private final StudentDao studentDao;
    private final TeacherDao teacherDao;
    private final JoinEntityDao joinEntityDao;
    private final More2BeanDao more2BeanDao;
    private final MoreBeanDao moreBeanDao;
    private final CourseDao courseDao;
    private final StudentsDao studentsDao;
    private final HeadDao headDao;
    private final PersonDao personDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        joinEntityDaoConfig = daoConfigMap.get(JoinEntityDao.class).clone();
        joinEntityDaoConfig.initIdentityScope(type);

        more2BeanDaoConfig = daoConfigMap.get(More2BeanDao.class).clone();
        more2BeanDaoConfig.initIdentityScope(type);

        moreBeanDaoConfig = daoConfigMap.get(MoreBeanDao.class).clone();
        moreBeanDaoConfig.initIdentityScope(type);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        studentsDaoConfig = daoConfigMap.get(StudentsDao.class).clone();
        studentsDaoConfig.initIdentityScope(type);

        headDaoConfig = daoConfigMap.get(HeadDao.class).clone();
        headDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        joinEntityDao = new JoinEntityDao(joinEntityDaoConfig, this);
        more2BeanDao = new More2BeanDao(more2BeanDaoConfig, this);
        moreBeanDao = new MoreBeanDao(moreBeanDaoConfig, this);
        courseDao = new CourseDao(courseDaoConfig, this);
        studentsDao = new StudentsDao(studentsDaoConfig, this);
        headDao = new HeadDao(headDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(JoinEntity.class, joinEntityDao);
        registerDao(More2Bean.class, more2BeanDao);
        registerDao(MoreBean.class, moreBeanDao);
        registerDao(Course.class, courseDao);
        registerDao(Students.class, studentsDao);
        registerDao(Head.class, headDao);
        registerDao(Person.class, personDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
        joinEntityDaoConfig.clearIdentityScope();
        more2BeanDaoConfig.clearIdentityScope();
        moreBeanDaoConfig.clearIdentityScope();
        courseDaoConfig.clearIdentityScope();
        studentsDaoConfig.clearIdentityScope();
        headDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public JoinEntityDao getJoinEntityDao() {
        return joinEntityDao;
    }

    public More2BeanDao getMore2BeanDao() {
        return more2BeanDao;
    }

    public MoreBeanDao getMoreBeanDao() {
        return moreBeanDao;
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public StudentsDao getStudentsDao() {
        return studentsDao;
    }

    public HeadDao getHeadDao() {
        return headDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

}
