package com.test.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.test.greendao.one_2_one.Head;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HEAD".
*/
public class HeadDao extends AbstractDao<Head, Long> {

    public static final String TABLENAME = "HEAD";

    /**
     * Properties of entity Head.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property HId = new Property(0, Long.class, "hId", true, "h_id");
        public final static Property HName = new Property(1, String.class, "hName", false, "h_name");
    }


    public HeadDao(DaoConfig config) {
        super(config);
    }
    
    public HeadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HEAD\" (" + //
                "\"h_id\" INTEGER PRIMARY KEY ," + // 0: hId
                "\"h_name\" TEXT);"); // 1: hName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HEAD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Head entity) {
        stmt.clearBindings();
 
        Long hId = entity.getHId();
        if (hId != null) {
            stmt.bindLong(1, hId);
        }
 
        String hName = entity.getHName();
        if (hName != null) {
            stmt.bindString(2, hName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Head entity) {
        stmt.clearBindings();
 
        Long hId = entity.getHId();
        if (hId != null) {
            stmt.bindLong(1, hId);
        }
 
        String hName = entity.getHName();
        if (hName != null) {
            stmt.bindString(2, hName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Head readEntity(Cursor cursor, int offset) {
        Head entity = new Head( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // hId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // hName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Head entity, int offset) {
        entity.setHId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Head entity, long rowId) {
        entity.setHId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Head entity) {
        if(entity != null) {
            return entity.getHId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Head entity) {
        return entity.getHId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
